application: army-knife
version: 1
runtime: python
api_version: 1

handlers:
- url: /sendmail
  script: sendmail.py

- url: /sendsms
  script: sendSMS.py

- url: /toodledo
  script: toodledo.py

- url: /.*
  script: not_found.py
